spring.application.name=auth-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# OpenTelemetry Logging
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:http://localhost:4318/v1/logs}
